FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    python3 \
    git \
    cargo \
    rust \
    libwebp-dev \
    nasm \
    perl \
    pkgconfig \
    cairo-dev \
    pango \
    gdk-pixbuf \
    jpeg-dev

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 1420 5173

CMD ["npm", "run", "dev"]